[package]
name = "folder-scan"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = "1.4"
rfd = "0.15.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
